class AppAssets {
  static const String appLogo = 'assets/images/app_logo.svg';
  static const String hoggaLight = 'assets/images/hoga_light.png';
  static const String hoggaDark = 'assets/images/hoga_dark.png';
  static const String applePay = 'assets/images/apple_pay.svg';
  static const String box = 'assets/images/box.svg';
  static const String calender = 'assets/images/calender_logo.svg';
  static const String carLogo = 'assets/images/car_logo.svg';
  static const String checkLogo = 'assets/images/check_logo.svg';
  static const String googleLogo =  'assets/images/google_logo.svg';
  static const String cutCircle = 'assets/images/cut_circle.svg';
  static const String discount = 'assets/images/discount_logo.svg';
  static const String doubleChat = 'assets/images/double_chat.svg';
  static const String delAccount = 'assets/images/remove_person.svg';
  static const String facebookLogo = 'assets/images/facebook_logo.svg';
  static const String filterLogo = 'assets/images/filter_logo.svg';
  static const String infoCircle =  'assets/images/info_circle.svg';
  static const String iconShare = 'assets/images/ion_share.svg';
  static const String mailLogo = 'assets/images/mail_logo.svg';
  static const String manLogo = 'assets/images/oman_logo.svg';
  static const String masterCardLogo = 'assets/images/master_card_logo.svg';
  static const String customerService = 'assets/images/customer_service.svg';
  static const String normalChat = 'assets/images/normal_chat.svg';
  static const String noteLogo = 'assets/images/note_logo.svg';
  static const String omanLogo = 'assets/images/oman_logo.svg';
  static const String paymentLogo = 'assets/images/payment_logo.svg';
  static const String logoutLogo = 'assets/images/logout_logo.svg';
  static const String mainNav = 'assets/images/main_nav.svg';
  static const String reciptNav = 'assets/images/recipt_logo.svg';
  static const String cartNav = 'assets/images/nav_cart.svg';
  static const String phoneLogo = 'assets/images/phone_logo.svg';
  static const String plusLogo = 'assets/images/plus_logo.svg';
  static const String qrcodeLogo = 'assets/images/qrcode_logo.svg';
  static const String questionMark = 'assets/images/question_mark.svg';
  static const String sendLogo = 'assets/images/send_logo.svg';
  static const String searchLogo = 'assets/images/search.svg';
  static const String solarCart = 'assets/images/solar_cart.svg';
  static const String star = 'assets/images/star.svg';
  static const String tiktokLogo = 'assets/images/tiktok_logo.svg';
  static const String trashLogo = 'assets/images/trash_logo.svg';
  static const String onboardingBackground = 'assets/images/onboarding_background.png';
  static const String tagerBackground = 'assets/images/tager_background.png';
  static const String person = 'assets/images/oman_logo.svg'; // Mapping person to manLogo if person is missing
  static const String profileNav = 'assets/images/oman_logo.svg'; // Mapping profileNav
  static const String cardLogo = 'assets/images/card_logo.svg';
  static const String shareLogo = 'assets/images/ion_share.svg';
  static const String heart = 'assets/images/solar_heart.svg'; // Assuming heart exists or using similar
  static const String moreNav = 'assets/images/more_nav.svg'; // Added moreNav
  static const String userPlaceholder = 'assets/images/user_placeholder.png';
  static const String authBackground = 'assets/images/auth_background.png';
}
